---
title: "LLegida de dades"
author: "Grup 02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LLEGIDA DADES
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Primer llegim les dues BBDD i les ordenem de la mateixa manera 
train <- read.csv2("train.csv",header=TRUE,sep=",")
train <- subset(train, select = -X)
train
test <- read.csv2("test.csv",header=TRUE,sep=",")
test

train <- train[, c("ID",sort(setdiff(names(train), c("ID","Exited"))),"Exited")]
test <- test[, c("ID", sort(setdiff(names(test), "ID")))]

#per veure les dues BBDD
train 
test 
```

#DEFINIR VARIABLES
```{r}
#per treballar de manera correcta cal que definim quines variables son veritablement de cada tipus

testbo <- test
#variables numèriques 
varsnum <- c("Age","AvgTransactionAmount", "Balance", "ComplaintsCount","CreditScore","DigitalEngagementScore", "EstimatedSalary","NetPromoterScore","NumOfProducts","Tenure","TransactionFrequency")

testbo[varsnum] <- lapply(testbo[varsnum], function(x) as.numeric(as.character(x)))
sapply(testbo[varsnum], function(x) sum(is.na(x)))

#variables categòriques

varscat <- setdiff(colnames(testbo), varsnum)

# Convertir las variables categóricas a factor
testbo[varscat] <- lapply(testbo[varscat], as.factor)


#modifiquem també les variables de train per si en un futur també volem treballar-hi (de la mateixa manera)

trainbo <- train

#variables numèriques 
varsnum <- c("Age","AvgTransactionAmount", "Balance", "ComplaintsCount","CreditScore","DigitalEngagementScore", "EstimatedSalary","NetPromoterScore","NumOfProducts","Tenure","TransactionFrequency")

trainbo[varsnum] <- lapply(trainbo[varsnum], function(x) as.numeric(as.character(x)))

#variables categòriques

varscat <- setdiff(colnames(trainbo), varsnum)

#Convertir las variables categóricas a factor
trainbo[varscat] <- lapply(trainbo[varscat], as.factor)
```

#crear bbdd amb tota la informació conjunta de test i train  
````{r}
library(dplyr)

#combinem els dos data frames (test i train)

dades <- bind_rows(
  testbo %>% mutate(Group = "test"),
  trainbo %>% mutate(Group= "train"))

#passem a factor la variable nova "group"
dades$Group <- as.factor(dades$Group)

naniar::mcar_test(dades)
````


#Generem un RData amb les dades que necessitem ja ben definides per treballar facilment
```{r}
save(trainbo, testbo, dades, varsnum,varscat, file = "bbddmineria.RData")
```

